package proyek;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import static java.sql.Types.NULL;
import javax.swing.JOptionPane;

/**
 *
 * @author asus
 */
public class frUser1 extends javax.swing.JFrame {
    int dragxmouse;
    int dragymouse;
    int harga=400000;
    String tujuan="Palembang";
    int jumlahDewasa;
    int jumlahAnak;
    int jumlahBayi;
    public frUser1() {
        initComponents();       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTujuan = new javax.swing.JComboBox();
        txtAsal = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        txtDay = new javax.swing.JComboBox();
        txtMonth = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtYear = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtJDewasa = new javax.swing.JComboBox();
        txtJAnak = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        txtJBayi = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JTextField();
        jPesan = new javax.swing.JLabel();
        buttonHitungharga = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtPesanan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(750, 525));
        setMinimumSize(new java.awt.Dimension(750, 525));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(750, 525));
        setResizable(false);
        setSize(new java.awt.Dimension(750, 525));
        getContentPane().setLayout(null);

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(700, 50, 40, 40);

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(700, 10, 40, 40);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102)), "Tujuan Penerbangan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Lato", 1, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Kota Asal        :");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Kota Tujuan    :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        txtTujuan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Palembang  - (Rp.400.000)", "Jakarta  - (Rp.450.000)", "Bandung  - (Rp.600.000)", "Jogja  - (Rp.850.000)" }));
        txtTujuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTujuanActionPerformed(evt);
            }
        });
        jPanel2.add(txtTujuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 280, 30));

        txtAsal.setMaximumRowCount(1);
        txtAsal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lampung", "Lampung", "Lampung", "Lampung" }));
        txtAsal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAsalActionPerformed(evt);
            }
        });
        jPanel2.add(txtAsal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 280, 30));

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 200, 360, 200);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)), "Tanggal Keberangkatan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lato", 1, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDay.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        txtDay.setMaximumRowCount(5);
        txtDay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        txtDay.setToolTipText("");
        txtDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDayActionPerformed(evt);
            }
        });
        jPanel1.add(txtDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 60, -1));

        txtMonth.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        txtMonth.setMaximumRowCount(5);
        txtMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month", "Januari", "februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        jPanel1.add(txtMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 120, -1));

        jLabel9.setText("-");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 50, -1));

        jLabel10.setText("-");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 20, -1));

        txtYear.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        txtYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year", "2019", "2020" }));
        jPanel1.add(txtYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 410, 360, 70);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)), "Jumlah Tiket Penumpang", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lato", 1, 14))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Dewasa");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Anak-Anak");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        txtJDewasa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5" }));
        txtJDewasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJDewasaActionPerformed(evt);
            }
        });
        jPanel3.add(txtJDewasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 100, -1));

        txtJAnak.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5" }));
        txtJAnak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJAnakActionPerformed(evt);
            }
        });
        jPanel3.add(txtJAnak, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 100, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Bayi");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        txtJBayi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5" }));
        txtJBayi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJBayiActionPerformed(evt);
            }
        });
        jPanel3.add(txtJBayi, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 100, -1));

        jLabel12.setFont(new java.awt.Font("Lato", 0, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("(18+ yrs)");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel13.setFont(new java.awt.Font("Lato", 0, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("(2 - 18 yrs)");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        jLabel14.setFont(new java.awt.Font("Lato", 0, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("(< 1 yrs)");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        getContentPane().add(jPanel3);
        jPanel3.setBounds(380, 200, 360, 120);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102)), "Total Harga ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lato", 1, 14))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Subtotal   :");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        txtSubtotal.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        txtSubtotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(txtSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 200, -1));

        getContentPane().add(jPanel4);
        jPanel4.setBounds(380, 370, 360, 100);

        jPesan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPesanMouseClicked(evt);
            }
        });
        getContentPane().add(jPesan);
        jPesan.setBounds(590, 480, 100, 30);

        buttonHitungharga.setBackground(new java.awt.Color(102, 204, 255));
        buttonHitungharga.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        buttonHitungharga.setForeground(new java.awt.Color(0, 0, 153));
        buttonHitungharga.setText("Hitung Harga");
        buttonHitungharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHitunghargaActionPerformed(evt);
            }
        });
        getContentPane().add(buttonHitungharga);
        buttonHitungharga.setBounds(590, 330, 130, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("No.Pesanan :");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(390, 330, 80, 30);

        txtPesanan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPesanan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPesanan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        txtPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesananActionPerformed(evt);
            }
        });
        getContentPane().add(txtPesanan);
        txtPesanan.setBounds(480, 330, 80, 30);

        jLabel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel6MouseDragged(evt);
            }
        });
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 750, 520);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyek/images/user1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 750, 525);

        setSize(new java.awt.Dimension(749, 520));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        this.setVisible(false);
        new frLogin1().setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        dragxmouse = evt.getX();
        dragymouse = evt.getY();
    }//GEN-LAST:event_jLabel6MousePressed

    private void jLabel6MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x-dragxmouse, y-dragymouse);
    }//GEN-LAST:event_jLabel6MouseDragged

    private void txtDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDayActionPerformed
        //
    }//GEN-LAST:event_txtDayActionPerformed

    private void txtJDewasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJDewasaActionPerformed
        int pilihan = txtJDewasa.getSelectedIndex();
        switch (pilihan){
                case 0:
                jumlahDewasa = NULL;
                break;
                case 1:
                jumlahDewasa = 1;
                break;
                case 2:
                jumlahDewasa = 2;
                break;
                case 3:
                jumlahDewasa = 3;
                break;
                case 4:
                jumlahDewasa = 4;
                break;
                case 5:
                jumlahDewasa = 5;
                break;
        }
    }//GEN-LAST:event_txtJDewasaActionPerformed

    private void txtJAnakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJAnakActionPerformed
        int pilihan = txtJAnak.getSelectedIndex();
        switch (pilihan){
                case 0:
                jumlahAnak = NULL;
                break;
                case 1:
                jumlahAnak = 1;
                break;
                case 2:
                jumlahAnak = 2;
                break;
                case 3:
                jumlahAnak = 3;
                break;
                case 4:
                jumlahAnak = 4;
                break;
                case 5:
                jumlahAnak = 5;
                break;
        }
    }//GEN-LAST:event_txtJAnakActionPerformed

    private void txtTujuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTujuanActionPerformed
        int pilihan = txtTujuan.getSelectedIndex();
        switch (pilihan){
                case 0:
                tujuan ="Palembang";
                harga = 400000;
                break;
                case 1:
                tujuan ="Jakarta";
                harga = 450000;
                break;
                case 2:
                tujuan ="Bandung";
                harga = 600000;
                break;
                case 3:
                tujuan ="Jogja";
                harga = 850000;
                break;
        }
    }//GEN-LAST:event_txtTujuanActionPerformed

    private void buttonHitunghargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHitunghargaActionPerformed
        int total = harga * (jumlahDewasa + jumlahAnak + jumlahBayi);
        txtSubtotal.setText("Rp."+total);
    }//GEN-LAST:event_buttonHitunghargaActionPerformed

    private void txtJBayiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJBayiActionPerformed
        int pilihan = txtJBayi.getSelectedIndex();
        switch (pilihan){
                case 0:
                jumlahBayi = NULL;
                break;
                case 1:
                jumlahBayi = 1;
                break;
                case 2:
                jumlahBayi = 2;
                break;
                case 3:
                jumlahBayi = 3;
                break;
                case 4:
                jumlahBayi = 4;
                break;
                case 5:
                jumlahBayi = 5;
                break;
        }
    }//GEN-LAST:event_txtJBayiActionPerformed

    private void txtAsalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAsalActionPerformed
        
    }//GEN-LAST:event_txtAsalActionPerformed

    private void jPesanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPesanMouseClicked
        int pes=0;
        try {
            pes++;
            String sql;
            sql = "INSERT INTO Data VALUES ('"+txtPesanan.getText()+"','"+txtDay.getSelectedItem()+"','"+txtMonth.getSelectedItem()+"','"+txtYear.getSelectedItem()
                    +"','"+txtAsal.getSelectedItem()+"','"+tujuan+"','"+txtJDewasa.getSelectedItem()+"','"+txtJAnak.getSelectedItem()+"','"+txtJBayi.getSelectedItem()+"','"+txtSubtotal.getText()+"')";
            java.sql.Connection conn=(Connection)koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Pembelian Tiket Anda Berhasil");
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        this.setVisible(false);
        new frUser2().setVisible(true);
    }//GEN-LAST:event_jPesanMouseClicked

    private void txtPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesananActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frUser1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frUser1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frUser1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frUser1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frUser1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonHitungharga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jPesan;
    private javax.swing.JComboBox txtAsal;
    private javax.swing.JComboBox txtDay;
    private javax.swing.JComboBox txtJAnak;
    private javax.swing.JComboBox txtJBayi;
    private javax.swing.JComboBox txtJDewasa;
    private javax.swing.JComboBox txtMonth;
    private javax.swing.JTextField txtPesanan;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JComboBox txtTujuan;
    private javax.swing.JComboBox txtYear;
    // End of variables declaration//GEN-END:variables
}
